name: Generate UML Diagram

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_PACKAGE_USER_NAME: ${{ github.actor }}
  GITHUB_PACKAGE_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:

  uml-diagram-report:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref }}

    - name: Checkout solidity workflows repository
      uses: actions/checkout@v4
      with:
        repository: The-Poolz/.net-workflows
        ref: master
        path: .net-workflows
  
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Install PlantUMLClassDiagramGenerator
      run: dotnet tool install --global PlantUmlClassDiagramGenerator

    - name: Increase PlantUML size limit
      run: echo "PLANTUML_LIMIT_SIZE=8192" >> $GITHUB_ENV

    - name: Run PlantUML server
      uses: docker://plantuml/plantuml-server:jetty
      with:
        ports: 8080:8080
        options: --detach --name plantuml

    - name: Generate UML Diagram using local PlantUML server
      run: |
        puml-gen ./ ./diagrams/ -dir -allInOne -createAssociation -excludePaths **/tests -s "http://localhost:8080"

    - name: Stop PlantUML server
      run: docker stop plantuml && docker rm plantuml

    - name: Download plantuml
      run: pip install plantuml

    - name: Write URL to file
      run: python .net-workflows/generate-uml-diagram-report.py
      env:
        FILE_PATH: ./diagrams/

    - name: Comment PR with URL
      uses: marocchino/sticky-pull-request-comment@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        recreate: true
        header: Diagram URL
        path: ${{github.workspace}}/uml-diagram-report.txt
